# Required values to support CI pipeline
environment: production
environmentCode:
name: fcp-fd-comms
namespace: fcp-fd
workstream: fcp-fd
image: fcp-fd-comms

appInsights:
  connectionString:

labels: {}

containerConfigMap:
  name: fcp-fd-comms-documents-config-map

containerSecret:
  name: fcp-fd-comms-container-secret
  type: Opaque

deployment: {}

port: &port 3039

container:
  resourceTier: M
  port: *port
  messageQueueHost: namespace.servicebus.windows.net
  commsSubscriptionAddress: fcp-fd-comms
  commsTopicAddress: fcp-fd-comms
  notifyApiKey:

# Enable if Managed Identity is required, ensure the clientID and resourceID are set in Platform Configuration
azureIdentity:
  enabled: true
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
