# Required values to support CI pipeline
environment: production
environmentCode:
name: fcp-fd-comms
namespace: fcp-fd
workstream: fcp-fd
image: fcp-fd-comms

appInsights:
  connectionString:

labels: {}

containerConfigMap: {}

containerSecret:
  name: fcp-fd-comms-container-secret
  type: Opaque

deployment: {}

port: &port 3039

container:
  resourceTier: M
  port: *port

livenessProbe:
  path: /healthz
  port: *port
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: *port
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

postgresService:
  postgresDb: fcp_fd_comms
  postgresExternalName:
  postgresHost: fcp-fd-comms-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

usePodIdentity: true

# Enable if Managed Identity is required, ensure the clientID and resourceID are set in Platform Configuration
azureIdentity:
  enabled: true
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID