# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-comms:
    build:
      target: development
    image: fcp-fd-comms-development
    container_name: fcp-fd-comms-development
    ports:
      - "3039:3039"
      - "9039:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

networks:
  fcp-fd-comms:
    name: fcp-fd-comms
    driver: bridge
