services:
  fcp-fd-comms:
    build:
      context: .
      target: production
    image: fcp-fd-comms
    container_name: fcp-fd-comms
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-comms-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      DATA_TOPIC_ADDRESS: fcp-fd-data${MESSAGE_QUEUE_SUFFIX}
      COMMS_TOPIC_ADDRESS: fcp-fd-comms${MESSAGE_QUEUE_SUFFIX}
      COMMS_SUBSCRIPTION_ADDRESS: fcp-fd-comms${MESSAGE_QUEUE_SUFFIX}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
      POSTGRES_DB: fcp_fd_comms
      POSTGRES_HOST: ${POSTGRES_HOST:-fcp-fd-comms-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      # below is only temporary and should be switch out once no longer needed
      USE_AZURITE: ${USE_AZURITE:-true}
      AZURITE_HOST: ${AZURITE_HOST:-http://fcp-fd-file-retriever-azurite-development}
      AZURITE_BLOB_PORT: ${AZURITE_BLOB_PORT:-10000}
      AZURITE_ACCESS_KEY: ${AZURITE_ACCESS_KEY:-test}
      OBJECTS_CONTAINER_NAME: objects-${MESSAGE_DEV_SUFFIX}
      DMZ_STORAGE_ACCOUNT_NAME: ${DMZ_STORAGE_ACCOUNT_NAME:-dmz}
      DMZ_STORAGE_ACCESS_KEY: ${DMZ_STORAGE_ACCESS_KEY:-test}
      CLN_STORAGE_ACCOUNT_NAME: ${CLN_STORAGE_ACCOUNT_NAME:-cln}
      CLN_STORAGE_ACCESS_KEY: ${CLN_STORAGE_ACCESS_KEY:-test}
      MAL_STORAGE_ACCOUNT_NAME: ${MAL_STORAGE_ACCOUNT_NAME:-mal}
      MAL_STORAGE_ACCESS_KEY: ${MAL_STORAGE_ACCESS_KEY:-test}
      ALLOW_TEXT_FILES: ${ALLOW_TEXT_FILES:-false}

  fcp-fd-comms-postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: fcp_fd_comms
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  fcp-fd-comms-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    container_name: fcp-fd-comms-azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"