# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-comms:
    build:
      target: development
    image: fcp-fd-comms-development
    container_name: fcp-fd-comms-development
    ports:
      - "3039:3039"
      - "9039:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json

  fcp-fd-comms-postgres:
    ports:
      - "5039:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  fcp-fd-file-retriever:
    name: fcp-fd-file-retriever
    driver: bridge
