services:
  fcp-fd-comms:
    build:
      context: .
      target: production
    image: fcp-fd-comms
    container_name: fcp-fd-comms
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-comms-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      DATA_TOPIC_ADDRESS: fcp-fd-data${MESSAGE_QUEUE_SUFFIX}
      COMMS_TOPIC_ADDRESS: fcp-fd-comms${MESSAGE_QUEUE_SUFFIX}
      COMMS_SUBSCRIPTION_ADDRESS: fcp-fd-comms${MESSAGE_QUEUE_SUFFIX}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
      POSTGRES_DB: fcp_fd_comms
      POSTGRES_HOST: ${POSTGRES_HOST:-fcp-fd-comms-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      FILE_RETRIEVER_HOST: ${FILE_RETRIEVER_HOST:-http://localhost:3042}
      # below is only temporary and should be switch out once no longer needed ---------------------
      OBJECTS_CONTAINER_NAME: objects-${MESSAGE_DEV_SUFFIX}
      CLN_STORAGE_ACCOUNT_NAME: ${CLN_STORAGE_ACCOUNT_NAME:-cln}
      CLN_STORAGE_ACCESS_KEY: ${CLN_STORAGE_ACCESS_KEY:-test}

  fcp-fd-comms-postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: fcp_fd_comms
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres