services:
  fcp-fd-comms:
    build:
      context: .
      target: production
    image: fcp-fd-comms
    container_name: fcp-fd-comms
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-comms-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
