services:
  fcp-fd-comms:
    build:
      context: .
      target: production
    image: fcp-fd-comms
    container_name: fcp-fd-comms
    depends_on: 
      - fcp-fd-comms-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-comms-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  fcp-fd-comms-postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: fcp-fd-comms
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres