# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-comms:
    build:
      target: development
    image: fcp-fd-comms-development
    container_name: fcp-fd-comms-development
    ports:
      - "3039:3039"
      - "9039:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    depends_on: 
      - fcp-fd-comms-azurite

  fcp-fd-comms-postgres:
    ports:
      - "5039:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fcp-fd-comms-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10019:10000"

volumes:
  postgres_data:
  azurite_data:

networks:
  fcp-fd-comms:
    name: fcp-fd
    driver: bridge
