# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-comms:
    build:
      target: development
    image: fcp-fd-comms-development
    container_name: fcp-fd-comms-development
    ports:
      - "3039:3039"
      - "9039:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    depends_on: 
      - fcp-fd-comms-azurite

  fcp-fd-comms-postgres:
    ports:
      - "5039:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # temporary, should be removed when not needed
  fcp-fd-comms-azurite:
    container_name: fcp-fd-comms-azurite-development
    networks:
      - fcp-fd-comms
    environment:
      AZURITE_ACCOUNTS: >
        ${DMZ_STORAGE_ACCOUNT_NAME:-dmz}:${AZURITE_ACCESS_KEY:-test};${CLN_STORAGE_ACCOUNT_NAME:-cln}:${AZURITE_ACCESS_KEY:-test};${MAL_STORAGE_ACCOUNT_NAME:-mal}:${AZURITE_ACCESS_KEY:-test}
    volumes:
      - azurite_data:/data

volumes:
  postgres_data:
  azurite_data:

networks:
  fcp-fd-comms:
    name: fcp-fd-comms # change back to fcp-fd before merging
    driver: bridge
