{{- include "ffc-helm-library.container-config-map" (list . "fcp-fd-comms.config-map") -}}
{{- define "fcp-fd-comms.config-map" -}}
data:
  MESSAGE_QUEUE_HOST: {{ .Values.container.messageQueueHost | quote }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  COMMS_TOPIC_ADDRESS: {{ .Values.container.commsTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  COMMS_TOPIC_ADDRESS: {{ .Values.container.commsTopicAddress | quote }}
  {{- end }}
  COMMS_SUBSCRIPTION_ADDRESS: {{ .Values.container.commsSubscriptionAddress }}
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
  CHECK_NOTIFY_STATUS_CRON_PATTERN: {{ .Values.container.checkNotifyStatusCronPattern | quote }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
{{- end -}}
