{{- include "ffc-helm-library.container-secret" (list . "fcp-fd-comms.container-secret") -}}
{{- define "fcp-fd-comms.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ .Values.appInsights.connectionString | quote }}
  {{- end }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
{{- end -}}
